### ISSUE TITLE
DAT's not working on Nov version update? 

### ISSUE THREAD

**Issue by CatsEyeXI** [KenshiDRK/XiView#6]
Hi there, are you aware of any issues where XiView is no longer working on the latest retail november version update?

**Comment by KenshiDRK** [comment]
Nothing was changed on the UI in the November update, so they should be working and are working for me.

**Comment by CatsEyeXI** [comment]
that's interesting.. 
When I realized this wasn't working via XIPivot in Ashiva-v4 I tried replacing the files in the FINAL FANTASY XI folder and I'm still not getting them to apply...  I'll have to brainstorm some more... not sure what's causing my issue at this point.
